export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const type      = searchParams.get('type')      || 'overall';
  const datasetId = searchParams.get('datasetId') || '';
  const formId    = searchParams.get('formId')    || '';
  const from      = searchParams.get('from')      || '';
  const to        = searchParams.get('to')        || '';

  const fromDate = from ? new Date(from) : null;
  const toDate   = to   ? new Date(new Date(to).setHours(23, 59, 59, 999)) : null;

  const filters = [
    from ? `From: ${from}` : '',
    to   ? `To: ${to}`     : '',
  ].filter(Boolean).join(', ') || 'All time';

  try {
    /* ── DATASET REPORT ── */
    if (type === 'dataset') {
      if (!datasetId) return NextResponse.json({ error: 'datasetId required' }, { status: 400 });

      const ds = await prisma.dataset.findUnique({ where: { id: datasetId } });
      if (!ds) return NextResponse.json({ error: 'Dataset not found' }, { status: 404 });

      let rows: Record<string, any>[] = [];
      try { rows = JSON.parse(ds.data); } catch {}
      if (!Array.isArray(rows)) rows = [];

      const colNames = rows.length > 0 ? Object.keys(rows[0]) : [];

      const colStats = colNames.map(col => {
        const vals = rows.map(r => r[col]);
        const nums = vals.map(Number).filter(n => !isNaN(n));
        if (nums.length / Math.max(vals.length, 1) >= 0.75 && nums.length > 0) {
          const sorted = [...nums].sort((a, b) => a - b);
          const mean   = nums.reduce((a, b) => a + b, 0) / nums.length;
          const median = sorted[Math.floor(sorted.length / 2)];
          const std    = Math.sqrt(nums.reduce((acc, n) => acc + (n - mean) ** 2, 0) / nums.length);
          const missing = vals.filter(v => v === null || v === undefined || v === '').length;
          return {
            column: col, type: 'numeric', count: nums.length,
            min: +sorted[0].toFixed(2), max: +sorted[sorted.length-1].toFixed(2),
            mean: +mean.toFixed(2), median: +median.toFixed(2), std: +std.toFixed(2),
            missing, missingPct: Math.round((missing / vals.length) * 100)
          };
        } else {
          const freq: Record<string, number> = {};
          vals.forEach(v => { const k = String(v ?? '(empty)'); freq[k] = (freq[k]||0)+1; });
          const sorted = Object.entries(freq).sort((a,b)=>b[1]-a[1]);
          const missing = vals.filter(v => v === null || v === undefined || v === '').length;
          return {
            column: col, type: 'categorical', count: vals.length,
            unique: Object.keys(freq).length,
            topValue: sorted[0]?.[0] || '-', topCount: sorted[0]?.[1] || 0,
            topValues: sorted.slice(0, 5).map(([v, c]) => ({ value: v, count: c })),
            missing, missingPct: Math.round((missing / vals.length) * 100)
          };
        }
      });

      const numericCols = colStats.filter(c => c.type === 'numeric').length;
      const catCols     = colStats.filter(c => c.type === 'categorical').length;
      const totalMissing = colStats.reduce((a, c) => a + (c.missing || 0), 0);
      const dataQuality  = Math.round(100 - (totalMissing / Math.max(rows.length * colNames.length, 1)) * 100);

      return NextResponse.json({
        title:       `Dataset Analysis Report — ${ds.filename}`,
        generatedAt: new Date().toISOString(),
        filters,
        author:      'DataCore Intelligence Platform',
        purpose:     'Automated statistical analysis of uploaded dataset',
        methodology: `This report was generated by analyzing ${rows.length.toLocaleString()} records across ${colNames.length} columns. Numeric columns were analyzed using descriptive statistics (mean, median, std dev). Categorical columns were analyzed using frequency distribution. Data quality was assessed by measuring null/missing values.`,
        summary:     `Dataset "${ds.filename}" contains ${rows.length.toLocaleString()} rows and ${colNames.length} columns (${numericCols} numeric, ${catCols} categorical). Overall data quality score: ${dataQuality}%. Uploaded on ${new Date(ds.uploadedAt).toLocaleDateString()}.`,
        metrics: [
          { label: 'Total Rows',      value: rows.length.toLocaleString(), color: '#6366f1' },
          { label: 'Total Columns',   value: colNames.length,              color: '#10b981' },
          { label: 'Numeric Cols',    value: numericCols,                  color: '#f59e0b' },
          { label: 'Category Cols',   value: catCols,                      color: '#ec4899' },
          { label: 'Data Quality',    value: `${dataQuality}%`,            color: dataQuality > 80 ? '#10b981' : '#f59e0b' },
          { label: 'Missing Values',  value: totalMissing,                 color: totalMissing > 0 ? '#ef4444' : '#10b981' },
        ],
        details: colStats,
        limitations: [
          'Analysis is based on data as uploaded — no external validation performed.',
          'Outlier detection uses basic statistical thresholds.',
          'Correlation analysis requires minimum 3 data points.',
          'Categorical columns with >50 unique values may have reduced accuracy.',
        ],
        context: { filename: ds.filename, rowCount: rows.length, columnCount: colNames.length, dataQuality, columns: colStats },
      });
    }

    /* ── FORM REPORT ── */
    if (type === 'form') {
      if (!formId) return NextResponse.json({ error: 'formId required' }, { status: 400 });

      // Fetch form with fields separately to avoid Prisma query issues
      const form = await prisma.form.findUnique({
        where:   { id: formId },
        include: { fields: { orderBy: { order: 'asc' } } },
      });
      if (!form) return NextResponse.json({ error: 'Form not found' }, { status: 404 });

      // Fetch submissions separately with optional date filter
      const submissionWhere: any = { formId };
      if (fromDate || toDate) {
        submissionWhere.submittedAt = {};
        if (fromDate) submissionWhere.submittedAt.gte = fromDate;
        if (toDate)   submissionWhere.submittedAt.lte = toDate;
      }

      const submissions = await prisma.formSubmission.findMany({
        where:   submissionWhere,
        orderBy: { submittedAt: 'desc' },
      });

      const parsed = submissions.map(s => { try { return JSON.parse(s.data); } catch { return {}; } });

      const fieldStats = form.fields.map(f => {
        const answers = parsed.map(d => d[f.label]).filter(v => v !== undefined && v !== '' && v !== null);
        const freq: Record<string, number> = {};
        answers.forEach(a => {
          const k = Array.isArray(a) ? a.join(', ') : String(a);
          freq[k] = (freq[k]||0)+1;
        });
        const topAnswers = Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,5);
        const responseRate = submissions.length > 0 ? Math.round((answers.length / submissions.length) * 100) : 0;
        return {
          field:        f.label,
          type:         f.type,
          responses:    answers.length,
          responseRate: `${responseRate}%`,
          topAnswers:   topAnswers.map(([v,c])=>`${v} (${c})`).join(' | '),
          topValues:    topAnswers.map(([v,c]) => ({ value: v, count: c })),
        };
      });

      const completionRate = form.fields.length > 0 && submissions.length > 0
        ? Math.round((parsed.reduce((acc, d) => acc + Object.values(d).filter(v => v !== '' && v !== null).length, 0)
            / (form.fields.length * submissions.length)) * 100)
        : 0;

      const firstResponse = submissions[submissions.length - 1];
      const lastResponse  = submissions[0];

      // Monthly trend
      const monthlyMap: Record<string, number> = {};
      submissions.forEach(s => {
        const month = new Date(s.submittedAt).toLocaleDateString('en-IN', { month: 'short', year: '2-digit' });
        monthlyMap[month] = (monthlyMap[month] || 0) + 1;
      });
      const monthlyTrend = Object.entries(monthlyMap).map(([month, count]) => ({ month, count }));

      return NextResponse.json({
        title:       `Form Response Report — ${form.title}`,
        generatedAt: new Date().toISOString(),
        filters,
        author:      'DataCore Intelligence Platform',
        purpose:     `Analysis of responses collected via form "${form.title}"`,
        methodology: `This report analyzes ${submissions.length} form responses collected ${filters !== 'All time' ? `between ${filters}` : 'across all time'}. Response rates, answer distributions, and completion rates were calculated for each of the ${form.fields.length} form fields. Frequency analysis was performed on categorical answers.`,
        summary:     `Form "${form.title}" received ${submissions.length} responses across ${form.fields.length} fields. Overall completion rate: ${completionRate}%. ${firstResponse ? `First response: ${new Date(firstResponse.submittedAt).toLocaleDateString()}. Latest response: ${new Date(lastResponse.submittedAt).toLocaleDateString()}.` : ''}`,
        metrics: [
          { label: 'Total Responses',   value: submissions.length,   color: '#6366f1' },
          { label: 'Form Fields',       value: form.fields.length,   color: '#10b981' },
          { label: 'Completion Rate',   value: `${completionRate}%`, color: completionRate > 70 ? '#10b981' : '#f59e0b' },
          { label: 'Avg Response Rate', value: `${Math.round(fieldStats.reduce((a,f)=>a+parseInt(f.responseRate),0)/Math.max(fieldStats.length,1))}%`, color: '#ec4899' },
          { label: 'First Response',    value: firstResponse ? new Date(firstResponse.submittedAt).toLocaleDateString() : 'N/A', color: '#8b5cf6' },
          { label: 'Latest Response',   value: lastResponse  ? new Date(lastResponse.submittedAt).toLocaleDateString()  : 'N/A', color: '#06b6d4' },
        ],
        details:      fieldStats,
        monthlyTrend,
        limitations: [
          'Open-ended text responses are not analyzed semantically.',
          'Response rate calculation assumes all fields are required.',
          'Trend data depends on submission timestamps being accurate.',
        ],
        context: {
          formTitle: form.title, totalSubmissions: submissions.length,
          completionRate, fields: fieldStats, monthlyTrend,
          dateRange: filters,
        },
      });
    }

    /* ── OVERALL REPORT ── */
    const [allSubmissions, datasets, forms] = await Promise.all([
      prisma.formSubmission.findMany({
        where:   (fromDate || toDate) ? { submittedAt: { ...(fromDate ? { gte: fromDate } : {}), ...(toDate ? { lte: toDate } : {}) } } : {},
        include: { form: true },
        orderBy: { submittedAt: 'desc' },
      }),
      prisma.dataset.findMany({ orderBy: { uploadedAt: 'desc' } }),
      prisma.form.findMany({ include: { _count: { select: { submissions: true } } } }),
    ]);

    let totalUploadedRows = 0;
    datasets.forEach(ds => {
      try { const d = JSON.parse(ds.data); if (Array.isArray(d)) totalUploadedRows += d.length; } catch {}
    });

    const formSummary = forms.map(f => ({
      form: f.title, submissions: f._count.submissions,
      created: new Date(f.createdAt).toLocaleDateString(),
    }));

    const topForm = forms.sort((a,b) => b._count.submissions - a._count.submissions)[0];

    return NextResponse.json({
      title:       'Executive Platform Report',
      generatedAt: new Date().toISOString(),
      filters,
      author:      'DataCore Intelligence Platform',
      purpose:     'Comprehensive overview of all data collection activities on the platform',
      methodology: `This executive report aggregates data from ${forms.length} active forms and ${datasets.length} uploaded datasets. Submission trends, completion rates, and data volume metrics were computed across all sources. ${filters !== 'All time' ? `Date range filter applied: ${filters}.` : 'All historical data included.'}`,
      summary:     `Platform overview: ${allSubmissions.length} form submissions from ${forms.length} forms, plus ${datasets.length} uploaded datasets containing ${totalUploadedRows.toLocaleString()} data rows. ${topForm ? `Most active form: "${topForm.title}" with ${topForm._count.submissions} responses.` : ''}`,
      metrics: [
        { label: 'Total Submissions', value: allSubmissions.length,           color: '#6366f1' },
        { label: 'Active Forms',      value: forms.length,                    color: '#10b981' },
        { label: 'Datasets Uploaded', value: datasets.length,                 color: '#f59e0b' },
        { label: 'Total Data Rows',   value: totalUploadedRows.toLocaleString(), color: '#ec4899' },
        { label: 'Top Form',          value: topForm?.title || 'N/A',         color: '#8b5cf6' },
        { label: 'Date Range',        value: filters,                         color: '#06b6d4' },
      ],
      details: formSummary,
      limitations: [
        'Report reflects data available at time of generation.',
        'Deleted forms and datasets are not included.',
        'Cross-form comparison assumes consistent field naming.',
      ],
      context: {
        totalSubmissions: allSubmissions.length, totalForms: forms.length,
        totalDatasets: datasets.length, totalUploadedRows,
        dateRange: filters, formSummary, topForm: topForm?.title,
      },
    });

  } catch (err: any) {
    console.error('[Reports V2 Error]', err);
    return NextResponse.json({ error: err.message || 'Failed to generate report' }, { status: 500 });
  }
}
